services:
  - type: web
    name: avap-support-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn avap_bot.bot:app --host 0.0.0.0 --port $PORT
    healthCheckPath: /health_check
    autoDeploy: true
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
    scaling:
      minInstances: 1
      maxInstances: 1